name: stockai
channels:
  - default
dependencies:
  - python=3.9
  - pip
  - pandas
  - pytorch
  - boto3
  - scikit-learn
  - jupyterlab
  - matplotlib
  - plotly
  - requests
  - yfinance
  - requests_cache
  # - conda-forge::pytorch-forecasting
  # - conda-forge::pytorch-forecasting[mqf2]
  # - conda-forge::torchdata
  # - conda-forge::torchmetrics
  - ipywidgets
  - pip:
    - lightning
    - pytorch-forecasting
    - fastapi
